- name: configure the cart component
  become: yes
  hosts: cart
  tasks:
   - name: default disable nodejs
     ansible.builtin.command: dnf module disable nodejs -y

   - name: enable nodejs
     ansible.builtin.command: dnf module enable nodejs:20 -y

   - name: Install nodejs 
     ansible.builtin.dnf:
      name: nodejs
      state: present

   - name: create a system user
     ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin   
      system: true
      home: /app

   - name: create app directory
     ansible.builtin.file:
      path: /app
      state: directory

   - name: download the  code
     ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      dest: /tmp/cart.zip

# this module thinks file exist on ansible control server, needs to extract on to remote machine
# remote_src: yes means files already exist in user server      

   - name: extract cart code
     ansible.builtin.unarchive:
        src: /tmp/cart.zip
        dest: /app
        remote_src: yes 

   - name: install the dependencies
     community.general.npm:
       path : /app

   - name: copying cart service to system directory
     ansible.builtin.copy:
       src: cart.service
       dest: /etc/systemd/system/cart.service

   - name: systemctl daemon reload
     ansible.builtin.systemd_service:
       daemon-reload: true

   - name: start and enable cart service
     ansible.builtin.service:
       name: cart
       state: started
       enabled: yes   

             
