[mongodb]
mongodb.malli.sbs
[catalogue]
catalogue.malli.sbs
[frontend]
frontend.malli.sbs
[redis]
redis.malli.sbs
[user]
user.malli.sbs
[cart]
cart.malli.sbs
[mysql]
mysql.malli.sbs
[shipping]
shipping.malli.sbs
[rabbitmq]
rabbitmq.malli.sbs
[payment]
payment.malli.sbs 
 
