- name: configure the user component
  become: yes
  hosts: user
  tasks:
   - name: Disable default module nodejs
     ansible.builtin.command: dnf module disable nodejs -y

   - name: enable default module nodejs
     ansible.builtin.command: dnf module enable nodejs:20 -y

   - name: Install nodejs
     ansible.builtin.dnf:
      name: nodejs
      state: present

    - name: create a directory
      ansible.builtin.file:
      path: /app
      state: directory

   - name: create a user roboshop
     ansible.builtin.user:
      name: roboshop
      create_home: yes

    - name: download the application
      ansible.builtin.get_url:
       url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip 
       dest: /tmp/user.zip

       


      
